# Generated by Django 5.2 on 2026-05-14 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('asignado', 'Asignado'), ('en_revision', 'En revisión'), ('pendiente_devolucion', 'Pendiente devolución'), ('dado_de_baja', 'Dado de baja')], default='disponible', max_length=25, verbose_name='Estado')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('motivo_baja', models.TextField(blank=True, null=True, verbose_name='Motivo de baja')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'db_table': 'activo',
            },
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10, verbose_name='Estado')),
                ('es_personalizado', models.BooleanField(default=False, verbose_name='Es personalizado')),
            ],
            options={
                'verbose_name': 'Tipo de Activo',
                'verbose_name_plural': 'Tipos de Activo',
                'db_table': 'tipo_activo',
            },
        ),
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de devolución')),
                ('estado_devolucion', models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('danado', 'Dañado'), ('con_perdida', 'Con pérdida')], max_length=15, null=True, verbose_name='Estado de devolución')),
                ('foto_evidencia', models.CharField(blank=True, max_length=500, null=True, verbose_name='Foto evidencia (ruta/URL)')),
                ('proceso_id', models.IntegerField(blank=True, null=True, verbose_name='ID del proceso origen')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='inventory.asset', verbose_name='Activo')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activos_asignados', to='workers.worker', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Asignación de Activo',
                'verbose_name_plural': 'Asignaciones de Activos',
                'db_table': 'asignacion_activo',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activos', to='inventory.assettype', verbose_name='Tipo'),
        ),
    ]
