# Generated by Django 5.2 on 2026-06-11 03:17

from django.db import migrations, models


def seed_ti_types(apps, schema_editor):
    AssetType = apps.get_model("inventory", "AssetType")
    tipos_ti = [
        ("Computador", "Computadores de escritorio y estaciones de trabajo"),
        ("Tablet", "Tablets y dispositivos móviles táctiles"),
        ("Notebook", "Laptops, notebooks y ultrabooks"),
        ("Monitor", "Monitores y pantallas"),
        ("Teléfono", "Teléfonos fijos y smartphones corporativos"),
        ("Impresora", "Impresoras, escáneres y multifuncionales"),
        ("Periférico", "Teclados, mouse, audífonos, webcams y otros periféricos"),
    ]
    for nombre, descripcion in tipos_ti:
        AssetType.objects.get_or_create(
            nombre=nombre,
            defaults={
                "descripcion": descripcion,
                "es_ti": True,
            },
        )
    AssetType.objects.filter(nombre="Equipos TI").update(es_ti=True)


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_assetassignment_foto_evidencia_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assettype",
            name="es_ti",
            field=models.BooleanField(default=False, verbose_name="Visible en TI"),
        ),
        migrations.RunPython(seed_ti_types, reverse_code=migrations.RunPython.noop),
    ]
