# Generated by Django 6.0.6 on 2026-06-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_asset_marca_asset_modelo_asset_numero_serie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetassignment',
            name='notas_devolucion',
            field=models.TextField(blank=True, null=True, verbose_name='Notas de devolución'),
        ),
    ]
