# Generated by Django 5.2 on 2026-05-14 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0001_initial"),
        ("workers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="costcenterhistory",
            name="proceso_id",
        ),
        migrations.AddField(
            model_name="costcenterhistory",
            name="proceso",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="processes.process",
                verbose_name="Proceso origen",
            ),
        ),
    ]
