# Generated by Django 5.2 on 2026-05-14 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('workers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('contratacion', 'Contratación'), ('cambio_ceco', 'Cambio de Centro de Costo'), ('termino', 'Término de Contrato'), ('despido', 'Despido')], max_length=15, verbose_name='Tipo')),
                ('estado', models.CharField(choices=[('en_curso', 'En curso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='en_curso', max_length=12, verbose_name='Estado')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inicio')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo')),
                ('causal_legal', models.TextField(blank=True, null=True, verbose_name='Causal legal')),
                ('requiere_confirmacion_rrhh', models.BooleanField(default=False)),
                ('ceco_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_destino', to='clients.costcenter', verbose_name='CeCo destino')),
                ('ceco_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_origen', to='clients.costcenter', verbose_name='CeCo origen')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='workers.worker', verbose_name='Trabajador')),
                ('usuario_inicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos_iniciados', to=settings.AUTH_USER_MODEL, verbose_name='Iniciado por')),
            ],
            options={
                'verbose_name': 'Proceso',
                'verbose_name_plural': 'Procesos',
                'db_table': 'proceso',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('crear_cuenta_ti', 'Creación de cuenta TI'), ('examenes_preocupacionales', 'Exámenes preocupacionales'), ('epp_induccion', 'EPP e Inducción'), ('equipamiento', 'Equipamiento'), ('devolucion_activos', 'Devolución de activos'), ('recuperacion_activos', 'Recuperación de activos'), ('preparar_bloqueo_accesos', 'Preparar bloqueo de accesos'), ('bloqueo_accesos', 'Bloqueo de accesos'), ('finiquito_coordinacion', 'Coordinación de finiquito')], max_length=30, verbose_name='Tipo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('completada', 'Completada'), ('vencida', 'Vencida'), ('escalada', 'Escalada'), ('gestionado_externo', 'Gestionado externo')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('urgencia', models.CharField(choices=[('normal', 'Normal'), ('critica', 'Crítica')], default='normal', max_length=10, verbose_name='Urgencia')),
                ('plazo_limite', models.DateTimeField(blank=True, null=True, verbose_name='Plazo límite')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha completado')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('omitida', models.BooleanField(default=False, verbose_name='Omitida')),
                ('motivo_omision', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo de omisión')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='processes.process', verbose_name='Proceso')),
                ('usuario_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'db_table': 'tarea',
                'ordering': ['-urgencia', 'plazo_limite'],
            },
        ),
    ]
