# Generated by Django 5.2 on 2026-06-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_taskdeadlineconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['orden', '-urgencia', 'plazo_limite'], 'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.AddField(
            model_name='task',
            name='orden',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Orden'),
        ),
    ]
