# Generated by Django 5.2 on 2026-06-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0005_alter_task_tipo_alter_taskdeadlineconfig_tipo_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='tipo',
            field=models.CharField(choices=[('contratacion', 'Contratación'), ('cambio_ceco', 'Cambio de Centro de Costo'), ('termino', 'Término de Contrato'), ('despido', 'Despido'), ('asignacion_activos', 'Asignación de Activos TI'), ('asignacion_epp', 'Asignación de EPP')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tipo',
            field=models.CharField(choices=[('crear_cuenta_ti', 'Creación de cuenta TI'), ('examenes_preocupacionales', 'Exámenes preocupacionales'), ('epp_induccion', 'EPP e Inducción'), ('equipamiento', 'Equipamiento'), ('devolucion_activos', 'Devolución de activos'), ('recuperacion_activos', 'Recuperación de activos'), ('preparar_bloqueo_accesos', 'Preparar bloqueo de accesos'), ('bloqueo_accesos', 'Bloqueo de accesos'), ('finiquito_coordinacion', 'Coordinación de finiquito'), ('asignar_equipo_ti', 'Asignación de Equipo TI'), ('devolucion_epp', 'Devolución de EPP'), ('asignar_epp', 'Asignación de EPP')], max_length=30, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='taskdeadlineconfig',
            name='tipo_tarea',
            field=models.CharField(choices=[('crear_cuenta_ti', 'Creación de cuenta TI'), ('examenes_preocupacionales', 'Exámenes preocupacionales'), ('epp_induccion', 'EPP e Inducción'), ('equipamiento', 'Equipamiento'), ('devolucion_activos', 'Devolución de activos'), ('recuperacion_activos', 'Recuperación de activos'), ('preparar_bloqueo_accesos', 'Preparar bloqueo de accesos'), ('bloqueo_accesos', 'Bloqueo de accesos'), ('finiquito_coordinacion', 'Coordinación de finiquito'), ('asignar_equipo_ti', 'Asignación de Equipo TI'), ('devolucion_epp', 'Devolución de EPP'), ('asignar_epp', 'Asignación de EPP')], max_length=30, unique=True, verbose_name='Tipo de tarea'),
        ),
    ]
