# Generated by Django 5.2 on 2026-05-14 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(db_index=True, max_length=100, verbose_name='Tipo de evento')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('canal', models.CharField(choices=[('correo', 'Correo electrónico'), ('interno', 'Interno')], max_length=10, verbose_name='Canal')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('leida', 'Leída'), ('eliminada', 'Eliminada')], default='pendiente', max_length=10, verbose_name='Estado')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('proceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='processes.process', verbose_name='Proceso')),
                ('tarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='processes.task', verbose_name='Tarea')),
                ('usuario_destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificacion',
                'ordering': ['-fecha_envio', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(max_length=100, verbose_name='Tipo de evento')),
                ('canal', models.CharField(choices=[('correo', 'Correo electrónico'), ('interno', 'Interno')], max_length=10, verbose_name='Canal')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('usuario_modifico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Configuración de notificación',
                'verbose_name_plural': 'Configuraciones de notificaciones',
                'db_table': 'config_notificacion',
                'unique_together': {('tipo_evento', 'canal')},
            },
        ),
    ]
